# Generated by Django 6.1.1 on 2026-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number. Never exposed publicly.', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
